// <auto-generated />
using AspNetCoreService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetCoreService.Data.MyMigrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220226212525_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AspNetCoreService.Data.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Content = "This is post 1 my interesting post",
                            Title = "post 1"
                        },
                        new
                        {
                            PostId = 2,
                            Content = "This is post 2 my interesting post",
                            Title = "post 2"
                        },
                        new
                        {
                            PostId = 3,
                            Content = "This is post 3 my interesting post",
                            Title = "post 3"
                        },
                        new
                        {
                            PostId = 4,
                            Content = "This is post 4 my interesting post",
                            Title = "post 4"
                        },
                        new
                        {
                            PostId = 5,
                            Content = "This is post 5 my interesting post",
                            Title = "post 5"
                        },
                        new
                        {
                            PostId = 6,
                            Content = "This is post 6 my interesting post",
                            Title = "post 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
